### ISSUE TITLE
Depends on apparmor cookbook

### ISSUE THREAD

**Issue by axos88** [sous-chefs/mysql#656] opened 2021-01-21 09:38 UTC
https://github.com/sous-chefs/mysql/blob/844036bde95721c401ce5309007787babdfc412d/libraries/mysql_service_base.rb#L126

Breaks if apparmor cookbook is not installed. Either needs to depends on that cookbook, or to leave out installation if apparmor attribute is undefined.
I also find it strange that the mysql cookbook is installing the apparmor package. Shouldn't that be left for the apparmor cookbook?

**Comment by axos88** [comment] 2021-01-21 09:42
Apparmor installation also breaks on ubuntu 20.04, due to missing template files

**Comment by axos88** [comment] 2021-01-21 10:14
Dupe of #654

**Comment by ramereth** [comment] 2021-01-25 23:00
Closing as duplicate of #654

**Closed by ramereth** 2021-01-25 23:00 UTC
